# Generated by Django 4.2.4 on 2024-02-23 18:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_company_logo_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Logo'),
        ),
    ]
