# Generated by Django 4.2.4 on 2023-10-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(null=True, upload_to='pages/', verbose_name='Image'),
        ),
    ]
