# Generated by Django 4.2.4 on 2023-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_page_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='key',
            field=models.CharField(default='pending', max_length=50, verbose_name='Unique Key'),
        ),
    ]
