# Generated by Django 4.2.4 on 2023-11-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_page_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50, verbose_name='Name')),
                ('logo', models.ImageField(upload_to='company/', verbose_name='Logo')),
                ('copy', models.CharField(max_length=150, verbose_name='Copy')),
                ('description', models.TextField(default='description', verbose_name='Description')),
                ('email', models.EmailField(default='email', max_length=254, verbose_name='Email')),
                ('github', models.URLField(default='github', verbose_name='GitHub')),
                ('linkedin', models.URLField(default='linkedin', verbose_name='LinkedIn')),
            ],
        ),
    ]
