# Generated by Django 4.2.4 on 2023-11-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
    ]
