# Generated by Django 4.2.4 on 2024-01-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pages/', verbose_name='Image'),
        ),
    ]
