# Generated by Django 4.2.4 on 2024-01-11 17:53

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pages/', validators=[home.models.validate_extension], verbose_name='Image'),
        ),
    ]
