# Generated by Django 4.2.4 on 2023-08-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='Category')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('show_hide', models.BooleanField(default=True, verbose_name='Show/Hide')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('specifications', models.TextField(verbose_name='Specifications')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured Product')),
                ('show_hide', models.BooleanField(default=True, verbose_name='Show/Hide')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Brand')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-updated_at', 'title'],
            },
        ),
    ]
