# Generated by Django 4.2.4 on 2024-02-22 18:00

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=django.utils.timezone.now, max_length=255, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image'),
        ),
    ]
