# Generated by Django 4.2.4 on 2023-08-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(choices=[(1, '1 month'), (3, '3 months'), (6, '6 months'), (12, '1 year'), (24, '2 years')], default='12'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
