# Generated by Django 4.2.4 on 2023-10-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_deal_productdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.DeleteModel(
            name='ProductDeal',
        ),
    ]
