# Generated by Django 4.2.4 on 2023-10-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_deal_products_delete_productdeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.deal', verbose_name='Deal'),
        ),
    ]
