# Generated by Django 4.2.4 on 2024-02-23 18:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_brand_slug_alter_category_slug_alter_deal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='no_image', max_length=255, verbose_name='Image'),
        ),
    ]
