# Generated by Django 4.2.4 on 2023-11-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='section',
        ),
    ]
