# Generated by Django 4.2.4 on 2024-02-23 18:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_deal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
    ]
