# Generated by Django 4.2.4 on 2023-09-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='father_category',
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'Section 1'), (3, 'Section 2'), (4, 'Section 3'), (5, 'Section 4')], default='1'),
        ),
    ]
