# Generated by Django 4.2.4 on 2023-11-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_deal_description_alter_deal_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/', verbose_name='Image'),
        ),
    ]
