# Generated by Django 4.2.4 on 2023-09-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_father_category_category_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='brand',
            name='show_hide',
            field=models.BooleanField(default=True, verbose_name='Show/Hide'),
        ),
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'Electronic Deals'), (3, 'TVs & Home Theater'), (4, 'Cell Phones'), (5, 'Computers & Office'), (6, 'Kids Electronics'), (7, 'Headphones'), (8, 'Cameras'), (9, 'Speakers & Audio Systems'), (10, 'Tablets & E-Readers'), (11, 'Wearable Technology'), (12, 'Wi-Fi & Networking')], default='1'),
        ),
    ]
