# Generated by Django 4.2.4 on 2023-11-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_deal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
