# Generated by Django 4.2.4 on 2023-09-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'title'], 'verbose_name_plural': 'Products'},
        ),
    ]
