# Generated by Django 4.2.4 on 2023-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
