# Generated by Django 4.2.4 on 2023-09-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, choices=[(1, '1 month'), (3, '3 months'), (6, '6 months'), (12, '1 year'), (24, '2 years'), (36, '3 years')], default='12', null=True),
        ),
    ]
