# Generated by Django 4.2.4 on 2024-01-23 20:06

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/', validators=[utils.validators.validate_extension], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[utils.validators.validate_extension], verbose_name='Image'),
        ),
    ]
